env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  space-before-function-paren: [1, 'always']
  ignorePatterns: [
    'bundle.js',
    'node_modules/',
    '__snapshots__/'
    ]
